language: python
python:
  - "3.6"

before_install:
# Upgrade pip setuptools and wheel
- pip install -U pip wheel setuptools

install:
  - pip install .[testing]
  - pip install coveralls
# command to run tests
script:
  - pytest --cov

after_success:
  - coveralls